# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\pageEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageEdit(object):
    def setupUi(self, PageEdit):
        PageEdit.setObjectName("PageEdit")
        PageEdit.resize(700, 600)
        font = QtGui.QFont()
        font.setPointSize(7)
        PageEdit.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(PageEdit)
        self.verticalLayout.setContentsMargins(36, 36, 36, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.knowledgeTitle = LineEdit(PageEdit)
        self.knowledgeTitle.setStyleSheet("background: rgba(0,0,0,0);border: 0;font-size: 29px")
        self.knowledgeTitle.setObjectName("knowledgeTitle")
        self.verticalLayout.addWidget(self.knowledgeTitle)
        self.commandBar = CommandBar(PageEdit)
        self.commandBar.setObjectName("commandBar")
        self.verticalLayout.addWidget(self.commandBar)
        self.SingleDirectionScrollArea = SingleDirectionScrollArea(PageEdit)
        self.SingleDirectionScrollArea.setStyleSheet("#mainWidget{border:1px solid rgba(120,120,120,80);border-radius:10px;background: rgba(0,0,0,0)}\n"
"#scrollAreaWidgetContents{border:1px solid rgba(120,120,120,80);border-radius:10px;background: rgba(0,0,0,0)}\n"
"#SingleDirectionScrollArea{border:1px solid rgba(120,120,120,80);border-radius:10px;background: rgba(0,0,0,0)}")
        self.SingleDirectionScrollArea.setWidgetResizable(True)
        self.SingleDirectionScrollArea.setObjectName("SingleDirectionScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 626, 474))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mainWidget = KnowledgeEditPad(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setStyleSheet("")
        self.mainWidget.setObjectName("mainWidget")
        self.horizontalLayout_3.addWidget(self.mainWidget)
        self.SingleDirectionScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.SingleDirectionScrollArea)

        self.retranslateUi(PageEdit)
        QtCore.QMetaObject.connectSlotsByName(PageEdit)

    def retranslateUi(self, PageEdit):
        _translate = QtCore.QCoreApplication.translate
        PageEdit.setWindowTitle(_translate("PageEdit", "Form"))
        self.knowledgeTitle.setText(_translate("PageEdit", "新的专题"))
from pwidgets import KnowledgeEditPad
from qfluentwidgets import CommandBar, LineEdit, SingleDirectionScrollArea
