# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\pageExamReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageExamReport(object):
    def setupUi(self, PageExamReport):
        PageExamReport.setObjectName("PageExamReport")
        PageExamReport.resize(700, 600)
        font = QtGui.QFont()
        font.setPointSize(7)
        PageExamReport.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(PageExamReport)
        self.verticalLayout.setContentsMargins(36, 36, 36, 9)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.knowledgeTitle = SubtitleLabel(PageExamReport)
        self.knowledgeTitle.setObjectName("knowledgeTitle")
        self.verticalLayout.addWidget(self.knowledgeTitle)
        self.titleLabel = TitleLabel(PageExamReport)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.CenterWidget = QtWidgets.QWidget(PageExamReport)
        self.CenterWidget.setObjectName("CenterWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CenterWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_1 = SubtitleLabel(self.CenterWidget)
        self.Label_1.setObjectName("Label_1")
        self.horizontalLayout.addWidget(self.Label_1)
        self.progressRing = ProgressRing(self.CenterWidget)
        self.progressRing.setTextVisible(True)
        self.progressRing.setObjectName("progressRing")
        self.horizontalLayout.addWidget(self.progressRing)
        self.verticalLayout.addWidget(self.CenterWidget)
        self.InfoWidget = QtWidgets.QWidget(PageExamReport)
        self.InfoWidget.setObjectName("InfoWidget")
        self.formLayout = QtWidgets.QFormLayout(self.InfoWidget)
        self.formLayout.setContentsMargins(16, -1, -1, -1)
        self.formLayout.setHorizontalSpacing(64)
        self.formLayout.setObjectName("formLayout")
        self.Label_3 = SubtitleLabel(self.InfoWidget)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.Label_4 = SubtitleLabel(self.InfoWidget)
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.missingLabel = SubtitleLabel(self.InfoWidget)
        self.missingLabel.setObjectName("missingLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.missingLabel)
        self.timeLabel = SubtitleLabel(self.InfoWidget)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeLabel)
        self.Label_2 = SubtitleLabel(self.InfoWidget)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.nOKnoeledgeLabel = SubtitleLabel(self.InfoWidget)
        self.nOKnoeledgeLabel.setObjectName("nOKnoeledgeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nOKnoeledgeLabel)
        self.verticalLayout.addWidget(self.InfoWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.returnButton = PushButton(PageExamReport)
        self.returnButton.setObjectName("returnButton")
        self.verticalLayout.addWidget(self.returnButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(PageExamReport)
        QtCore.QMetaObject.connectSlotsByName(PageExamReport)

    def retranslateUi(self, PageExamReport):
        _translate = QtCore.QCoreApplication.translate
        PageExamReport.setWindowTitle(_translate("PageExamReport", "Form"))
        self.knowledgeTitle.setText(_translate("PageExamReport", "专题"))
        self.titleLabel.setText(_translate("PageExamReport", "测试完成"))
        self.Label_1.setText(_translate("PageExamReport", "掌握度已更新"))
        self.Label_3.setText(_translate("PageExamReport", "用时："))
        self.Label_4.setText(_translate("PageExamReport", "缺漏："))
        self.missingLabel.setText(_translate("PageExamReport", "Subtitle label"))
        self.timeLabel.setText(_translate("PageExamReport", "Subtitle label"))
        self.Label_2.setText(_translate("PageExamReport", "知识数："))
        self.nOKnoeledgeLabel.setText(_translate("PageExamReport", "Subtitle label"))
        self.returnButton.setText(_translate("PageExamReport", "返回主页"))
from qfluentwidgets import ProgressRing, PushButton, SubtitleLabel, TitleLabel
