# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\pageLibrary.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageLibrary(object):
    def setupUi(self, PageLibrary):
        PageLibrary.setObjectName("PageLibrary")
        PageLibrary.resize(700, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(PageLibrary)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBar = QtWidgets.QWidget(PageLibrary)
        self.topBar.setMinimumSize(QtCore.QSize(0, 30))
        self.topBar.setObjectName("topBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topBar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.collationSelector = TransparentDropDownPushButton(self.topBar)
        self.collationSelector.setObjectName("sortSelector")
        self.horizontalLayout.addWidget(self.collationSelector)
        self.filterSelector = TransparentDropDownPushButton(self.topBar)
        self.filterSelector.setObjectName("filterSelector")
        self.horizontalLayout.addWidget(self.filterSelector)
        self.addKnowledge = TransparentToolButton(self.topBar)
        self.addKnowledge.setObjectName("addKnowledge")
        self.horizontalLayout.addWidget(self.addKnowledge)
        self.verticalLayout.addWidget(self.topBar)
        self.knowledgeTable = TableWidget(PageLibrary)
        self.knowledgeTable.setObjectName("knowledgeTable")
        self.knowledgeTable.setColumnCount(0)
        self.knowledgeTable.setRowCount(0)
        self.verticalLayout.addWidget(self.knowledgeTable)

        self.retranslateUi(PageLibrary)
        QtCore.QMetaObject.connectSlotsByName(PageLibrary)

    def retranslateUi(self, PageLibrary):
        _translate = QtCore.QCoreApplication.translate
        PageLibrary.setWindowTitle(_translate("PageLibrary", "Form"))
        self.collationSelector.setText(_translate("PageLibrary", "创建日期"))
        self.filterSelector.setText(_translate("PageLibrary", "无筛选"))
from qfluentwidgets import TableWidget, TransparentDropDownPushButton, TransparentToolButton
